#pragma once
#include "ratelimit/export.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Library version string (from version.h generated by CMake)
RL_API const char* rl_version(void);

typedef struct {
    uint64_t capacity;
    uint64_t refill_per_sec;
} rl_limit_t;

typedef struct {
    uint8_t  allowed;
    uint64_t remaining;
    uint64_t reset_ms;
} rl_decision_t;

// C wrapper for the in-process rate limiter
RL_API void*        rl_new_inproc(unsigned shards, unsigned capacity_hint_per_shard);
RL_API rl_decision_t rl_allow(void* handle, const char* key, rl_limit_t limit);
RL_API void         rl_free(void* handle);

#ifdef __cplusplus
}
#endif
